// AUTO-GENERATED by E2E Quality Gate — 2026-04-28
// Master Test Plan items: A1-A14 (functional flow + tab navigation)
// Run: npx playwright test tests/e2e/01-functionality.spec.ts

import { test, expect, type Page } from '@playwright/test';

const BASE_URL = process.env.HQ_URL || 'https://vieforce-hq.vercel.app';
const PHONE = process.env.HQ_TEST_PHONE || '09170000100';  // CEO test account
const PIN = process.env.HQ_TEST_PIN || '2026';

async function login(page: Page) {
  await page.goto(`${BASE_URL}/index.html`);
  await page.getByRole('textbox', { name: 'Phone Number' }).fill(PHONE);
  await page.getByRole('textbox', { name: 'PIN' }).fill(PIN);
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.waitForURL(/app\.html/, { timeout: 10_000 });
}

test.describe('VieForce HQ — Login & Tabs', () => {
  test.use({ viewport: { width: 1920, height: 1080 } });

  test('A1 — Login page renders', async ({ page }) => {
    await page.goto(`${BASE_URL}/index.html`);
    await expect(page).toHaveTitle('VieForce HQ — Login');
    await expect(page.getByRole('button', { name: 'Sign In' })).toBeVisible();
  });

  test('A2 — Login with CEO PIN succeeds', async ({ page }) => {
    await login(page);
    await expect(page).toHaveTitle('VieForce HQ — Desktop');
    await expect(page.locator('text=Mathieu Guillaume').first()).toBeVisible();
  });

  test('A3 — Wrong PIN rejected', async ({ page }) => {
    await page.goto(`${BASE_URL}/index.html`);
    await page.getByRole('textbox', { name: 'Phone Number' }).fill(PHONE);
    await page.getByRole('textbox', { name: 'PIN' }).fill('0000');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await expect(page.locator('text=/incorrect pin/i')).toBeVisible({ timeout: 5000 });
  });

  // Walk every tab — fail if any tab errors or shows blank
  const tabs = [
    { id: 'pg-evp-home', label: 'EVP Dashboard', expect: /Good (morning|afternoon|evening), Mathieu/i },
    { id: 'pg-home',     label: 'National Dashboard', expect: /National Overview/i },
    { id: 'pg-sales',    label: 'Sales',           expect: /(MTD VOLUME|CUSTOMER RANKINGS)/i },
    { id: 'pg-ar',       label: 'Accounts Receivable', expect: /(ACTIVE AR|DELINQUENT AR|AR AGING)/i },
    { id: 'pg-inv',      label: 'Inventory',       expect: /(ON FLOOR|BY REGION|BY PLANT)/i },
    { id: 'pg-speed',    label: 'Speed Monitor',   expect: /(DAILY PULLOUT|WEEKLY MATRIX)/i },
    { id: 'pg-customers', label: 'Customers',      expect: /(NET SALES|GM\/TON)/i },
    { id: 'pg-insights', label: 'Customer Intelligence', expect: /(RESCUE|GROW|EARLY WARNING)/i },
    { id: 'pg-margin',   label: 'Margin Alerts',   expect: /(CRITICAL|WARNING|WATCH|HEALTHY)/i },
    { id: 'pg-team',     label: 'Sales Team',      expect: /(L10 SCORECARD|RSM SCORECARD)/i },
    { id: 'pg-budget',   label: 'Budget & P&L',    expect: /(Sales Volume Budget|TOTAL GROSS MARGIN)/i },
    { id: 'pg-itemized', label: 'Itemized Sales',  expect: /(VIEPRO|Filter SKUs)/i },
  ];

  for (const tab of tabs) {
    test(`A4-${tab.id} — ${tab.label} loads with content`, async ({ page }) => {
      await login(page);
      const errors: string[] = [];
      page.on('pageerror', e => errors.push(e.message));
      await page.evaluate((id) => (window as any).navTo(id), tab.id);
      await page.waitForTimeout(2500);
      const container = page.locator(`#${tab.id}`);
      await expect(container).toBeVisible();
      await expect(container).toContainText(tab.expect);
      expect(errors, `console errors on ${tab.id}`).toEqual([]);
    });
  }
});
