// AUTO-GENERATED by E2E Quality Gate — 2026-04-28
// Master Test Plan items: B1-B5 (interactive toggles, theme, search)

import { test, expect, type Page } from '@playwright/test';

const BASE_URL = process.env.HQ_URL || 'https://vieforce-hq.vercel.app';
const PHONE = process.env.HQ_TEST_PHONE || '09170000100';
const PIN = process.env.HQ_TEST_PIN || '2026';

async function login(page: Page) {
  await page.goto(`${BASE_URL}/index.html`);
  await page.getByRole('textbox', { name: 'Phone Number' }).fill(PHONE);
  await page.getByRole('textbox', { name: 'PIN' }).fill(PIN);
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.waitForURL(/app\.html/);
  await page.waitForTimeout(3000);  // allow initial data load
}

test.use({ viewport: { width: 1920, height: 1080 } });

test('B1 — Global Bags/MT toggle switches instantly without new API call', async ({ page }) => {
  await login(page);
  // Capture network calls before clicking
  const apiBefore = await page.evaluate(() =>
    performance.getEntriesByType('resource').filter(r => r.name.includes('/api/')).length
  );
  // Click Bags pill in the global header toggle
  await page.locator('.tb-toggle-btn[onclick="setU(this)"]').filter({ hasText: 'Bags' }).click();
  await page.waitForTimeout(500);
  const apiAfter = await page.evaluate(() =>
    performance.getEntriesByType('resource').filter(r => r.name.includes('/api/')).length
  );
  expect(apiAfter, 'unit toggle should NOT trigger new API requests').toBe(apiBefore);
  await expect(page.locator('.tb-toggle-btn[onclick="setU(this)"]').filter({ hasText: 'Bags' })).toHaveClass(/active/);
});

test('B2 — Theme toggle switches dark↔light', async ({ page }) => {
  await login(page);
  const themeBefore = await page.evaluate(() => document.documentElement.getAttribute('data-theme') || 'dark');
  await page.locator('[onclick*="theme"], [onclick*="Theme"]').first().click();
  const themeAfter = await page.evaluate(() => document.documentElement.getAttribute('data-theme') || 'dark');
  expect(themeAfter).not.toBe(themeBefore);
});

test('B3 — Period buttons (MTD/QTD/YTD) trigger refetch with correct params', async ({ page }) => {
  await login(page);
  const apiCalls: string[] = [];
  page.on('request', r => {
    if (r.url().includes('/api/')) apiCalls.push(r.url());
  });
  // Click QTD
  const qtdBtn = page.locator('button, .tb-toggle-btn').filter({ hasText: /^QTD$/ }).first();
  if (await qtdBtn.count() > 0) {
    await qtdBtn.click();
    await page.waitForTimeout(2500);
    const qtdCalls = apiCalls.filter(u => u.includes('period=QTD'));
    expect(qtdCalls.length, 'QTD click should fire QTD API request').toBeGreaterThan(0);
  }
});

test('B4 — Logout clears session and redirects to login', async ({ page }) => {
  await login(page);
  // Find logout — usually in a More menu or sidebar
  await page.evaluate(() => {
    if (typeof (window as any).logout === 'function') (window as any).logout();
  });
  await page.waitForTimeout(1500);
  await expect(page).toHaveURL(/index\.html/);
  // Session storage should be cleared
  const session = await page.evaluate(() => localStorage.getItem('vf_session'));
  expect(session).toBeNull();
});

test('B5 — Mobile viewport (375x812) renders bottom-nav layout', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await login(page);
  await page.waitForTimeout(2000);
  // Bottom nav should be visible on mobile
  const bottomNav = page.locator('text=/^(Home|P&L|Margin|Team|More)$/').first();
  await expect(bottomNav).toBeVisible();
});
