// AUTO-GENERATED by E2E Quality Gate — 2026-04-28
// Master Test Plan items: C1-C16 (API health probes)
// These hit the Cloud Run backend directly with the user's session token

import { test, expect, type APIRequestContext, request as pwRequest } from '@playwright/test';

const HQ_URL = process.env.HQ_URL || 'https://vieforce-hq.vercel.app';
const API_URL = process.env.HQ_API_URL || 'https://vieforce-hq-api-1057619753074.asia-southeast1.run.app';
const PHONE = process.env.HQ_TEST_PHONE || '09170000100';
const PIN = process.env.HQ_TEST_PIN || '2026';

// Helper — login through the browser to get a session-id cookie
async function getSessionId(): Promise<string> {
  const ctx = await pwRequest.newContext();
  // The HQ login is browser-driven (writes to localStorage), so we mimic it by
  // calling supabase directly. For a quick health check we'll just verify
  // unauthenticated endpoints respond with 401 (proving auth is wired).
  await ctx.dispose();
  return '';  // Health checks below intentionally hit without auth to verify 401 path
}

const ENDPOINTS = [
  '/api/dashboard?period=MTD&region=ALL',
  '/api/sales?period=MTD&region=ALL',
  '/api/ar',
  '/api/speed?period=MTD',
  '/api/inventory?plant=ALL',
  '/api/customers?limit=100',
  '/api/intelligence?period=MTD',
  '/api/margin?period=MTD',
  '/api/team',
  '/api/budget',
  '/api/itemized?district=TOTAL+NATIONAL+2026&year=2026',
  '/api/itemized/meta',
  '/api/silenced',
  '/api/analytics/sku-matrix?unit=volume&region=ALL&bu=ALL',
  '/api/analytics/brand-coverage',
  '/api/analytics/buying-patterns',
];

test.describe('API Health — Cloud Run backend responds (or rejects unauthorized)', () => {
  for (const ep of ENDPOINTS) {
    test(`C-${ep.split('?')[0].split('/').slice(-1)[0]} — ${ep}`, async ({ request }) => {
      const start = Date.now();
      const resp = await request.get(`${API_URL}${ep}`);
      const elapsed = Date.now() - start;
      // Without session, should be 401 (proves auth is enforced).
      // With session, should be 200. Either is acceptable here — the failure
      // mode we're guarding against is 502/504/timeout.
      expect([200, 401], `${ep} returned unexpected status`).toContain(resp.status());
      expect(elapsed, `${ep} took longer than 5s`).toBeLessThan(5000);
    });
  }

  test('C-undefined-bug — initial dashboard call should NOT use literal "undefined"', async ({ request }) => {
    // KNOWN BUG documented in QG report 2026-04-28:
    // Frontend fires /api/dashboard?period=undefined&region=undefined on initial load.
    // This test FAILS today and is expected to PASS after the bug is fixed.
    const resp = await request.get(`${API_URL}/api/dashboard?period=undefined&region=undefined`);
    // If the fix is applied, the backend should reject undefined as 400.
    // Until then, it returns 200 (silently handling it).
    expect.soft(resp.status(), 'Backend should reject literal "undefined" with 400 once frontend is fixed').toBe(400);
  });
});
