// AUTO-GENERATED by E2E Quality Gate — 2026-04-28
// Run: pnpm add -D @axe-core/playwright   (then) npx playwright test tests/e2e/08-accessibility.spec.ts

import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const BASE_URL = process.env.HQ_URL || 'https://vieforce-hq.vercel.app';
const PHONE = process.env.HQ_TEST_PHONE || '09170000100';
const PIN = process.env.HQ_TEST_PIN || '2026';

async function login(page: Page) {
  await page.goto(`${BASE_URL}/index.html`);
  await page.getByRole('textbox', { name: 'Phone Number' }).fill(PHONE);
  await page.getByRole('textbox', { name: 'PIN' }).fill(PIN);
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.waitForURL(/app\.html/);
  await page.waitForTimeout(3000);
}

test.use({ viewport: { width: 1920, height: 1080 } });

test('I1 — Login page has zero serious/critical a11y violations', async ({ page }) => {
  await page.goto(`${BASE_URL}/index.html`);
  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze();
  const blocking = results.violations.filter(v => v.impact === 'serious' || v.impact === 'critical');
  expect(blocking, JSON.stringify(blocking, null, 2)).toEqual([]);
});

test('I2 — Home (post-login) has zero serious/critical a11y violations', async ({ page }) => {
  await login(page);
  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze();
  const blocking = results.violations.filter(v => v.impact === 'serious' || v.impact === 'critical');
  expect(blocking, JSON.stringify(blocking, null, 2)).toEqual([]);
});

test('I3 — Color contrast ≥ 4.5:1 across visible tabs', async ({ page }) => {
  await login(page);
  const results = await new AxeBuilder({ page }).withRules(['color-contrast']).analyze();
  expect(results.violations).toEqual([]);
});
